config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'static_pages#home'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy

  before_save { email.downcase! }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.where("user_id = ?", id)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private

    def micropost_params
      params.require(:micropost).permit(:content)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :new_user, only: [:new, :create]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :no_self_delete, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # Before filters

    def new_user
      if signed_in?
        redirect_to root_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def no_self_delete
      @user = User.find(params[:id])
      redirect_to(root_url) if current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    a> href="http://railstutorial.org/" Rails Tutorial
    | by Michael Hartl
  nav
    ul
      li == link_to "About", about_path
      li == link_to "Contact", contact_path
      li: a href="http://news.railstutorial.org/" News

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      == link_to "sample app", '#', id: "logo"
      nav
        ul.nav.pull-right.navbar-nav
          li == link_to "Home", root_path
          li == link_to "Help", help_path
          - if signed_in?
            li == link_to "Users", users_path
            li#fat-menu.dropdown
              a.dropdown-toggle data-toggle="dropdown" href="#"
                | Account
                b.caret<
              ul.dropdown-menu
                li == link_to "Profile", current_user
                li == link_to "Settings", edit_user_path(current_user)
                li.divider
                li == link_to "Sign out", signout_path, method: "delete"
          - else
            li == link_to "Sign in", signin_path

app/views/layouts/_shim.html.slim
/[if lt IE 9]
  script src="http://html5shim.googlecode.com/svn/html5.js"

app/views/layouts/application.html.slim
doctype html
html
  head
    title = full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        div class="alert alert-#{key}" = value
      = yield
      = render 'layouts/footer'
      - if Rails.env.development?
        = debug(params)
        = debug(request.authorization)
        = debug(request.content_length)
        = debug(request.flash)
        = debug(request.fullpath)
        = debug(request.ip)
        = debug(request.media_type)

app/views/microposts/_micropost.html.slim
li
  span.content = micropost.content
  span.timestamp
    | Posted
    =<> time_ago_in_words(micropost.created_at)
    | ago.
  - if current_user?(micropost.user)
    = link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" }, title: micropost.content

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      | The form contains
      =< pluralize(object.errors.count, "error")
    ul
      - object.errors.full_messages.each do |msg|
        li = "* " + msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    = render partial: 'shared/feed_item', collection: @feed_items
  = will_paginate @feed_items

app/views/shared/_feed_item.html.slim
li id=feed_item.id
  = link_to gravatar_for(feed_item.user), feed_item.user
  span.user = link_to feed_item.user.name, feed_item.user
  span.content = feed_item.content
  span.timestamp
    | Posted
    =<> time_ago_in_words(feed_item.created_at)
    | ago.
  - if current_user?(feed_item.user)
    = link_to "delete", feed_item, method: :delete, data: { confirm: "You sure?" }, title: feed_item.content

app/views/shared/_micropost_form.html.slim
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 52), current_user
h1 = current_user.name
span = link_to "view my profile", current_user
span = pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/about.html.slim
- provide(:title, 'About Us')
h1 About Us
p
  | The
  a<> href="http://railstutorial.org/" Ruby on Rails Tutorial
  | is a project to make a book and screencasts to teach web development with
  a< href="http://rubyonrails.org/" Ruby on Rails
  | . This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.slim
- provide(:title, 'Contact')
h1 Contact
p
  | Contact Ruby on Rails Tutorial about the sample app at the
  a< href="http://railstutorial.org/contact" contact page
  | .

app/views/static_pages/help.html.slim
- provide(:title, 'Help')
h1 Help
p
  | Get help on the Ruby on Rails Tutorial at the
  a< href="http://railstutorial.org/help" Rails Tutorial help page
  | . To get help on this sample app, see the
  a< href="http://railstutorial.org/book" Rails Tutorial book
  | .

app/views/static_pages/home.html.slim
- if signed_in?
  .row
    aside.span4
      section
        = render 'shared/user_info'
      section
        = render 'shared/micropost_form'
    .span8
      h3 Micropost Feed
      = render 'shared/feed'
- else
  .center.jumbotron
    h1 Welcome to the Sample App
    h2
      | This is the home page for the
      a<> href="http://railstutorial.org/" Ruby on Rails Tutorial
      | sample application.

    == link_to "Sign up now!", signup_path, class: "btn btn-larg btn-primary"
  == link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/users/_fields.html.slim
= render 'shared/error_messages', object: f.object

= f.label :name
= f.text_field :name

= f.label :email
= f.text_field :email

= f.label :password
= f.password_field :password

= f.label :password_confirmation, "Confirm Password"
= f.password_field :password_confirmation

app/views/users/_user.html.slim
li
  == gravatar_for user, size: 52
  == link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    |  |
    ==< link_to "delete", user, method: :delete, data: { confirm: "You sure?" }

app/views/users/edit.html.slim
- provide(:title, "Edit user")
h1 Update your profile

.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'shared/error_messages', object: f.object

      = f.label :name
      = f.text_field :name

      = f.label :email
      = f.text_field :email

      = f.label :password
      = f.password_field :password

      = f.label :password_confirmation, "Confirm Password"
      = f.password_field :password_confirmation

      = f.submit "Save changes", class: "btn btn-large btn-primary"

    = gravatar_for @user
    a href="http://gravatar.com/emails" target="_blank" change

app/views/users/index.html.slim
- provide(:title, 'All users')
h1 All users

== will_paginate

ul.users
  == render @users

== will_paginate

app/views/users/new.html.slim
- provide(:title, 'Sign up')
h1 Sign up
.row
  .span6.offset3
    = form_for(@user) do |f|
      = render 'fields', f: f
      = f.submit "Create my account", class: "btn btn-large btn-primary"

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
  aside.span4
    h1
      ==> gravatar_for @user
      = @user.name
  .span8
    - if @user.microposts.any?
      h3 Microposts #{@user.microposts.count}
      ol.microposts
        = render @microposts
      = will_paginate @microposts